apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  # label for StatefulSet
  labels:
    app: wordpress-mysql 
spec:
  serviceName: mysql-master
  replicas: 1
  selector:
    # label for ReplicaSet
    matchLabels:
      app: wordpress-mysql
  template:
    metadata:
      # label for pod
      labels:
        app: wordpress-mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-pass
                  key: mysql_root_pass.txt
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-volumeclaim
  