apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo 
  labels:
    app: echo 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo 
  template: # template以下はPodリソースにおけるspec定義と同じ
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: nginx 
        image: nginx:latest 
        env: 
        - name: BACKEND_HOST
          value: localhost:8080
        ports:
        - containerPort: 80 
        command:
            - sh
            - -c
            - while true; do echo $(hostname):a; sleep 10; done
      - name: echo
        image: hashicorp/http-echo:latest
        ports:
        - containerPort: 8080
        command:
            - sh
            - -c
            - while true; do echo $(hostname):a; sleep 10; done
